//! Self-update: check for a newer GitHub release, download the platform
//! asset, verify its SHA256, and swap the running binary in place.
//!
//! Design (see plans/self-update.md):
//! - Version + checksum manifest `latest.json`, served as a release asset at
//!   `releases/latest/download/latest.json` — a GitHub CDN redirect with no
//!   api.github.com rate limit. `RHD_UPDATE_BASE` overrides the base URL
//!   entirely (mirrors; same contract as the installers' RHD_DOWNLOAD_BASE).
//! - The HTTP client here is deliberately separate from `http_client.rs`:
//!   update traffic must never carry the HuggingFace token.
//! - The swap is delegated to `self_replace` (Unix: atomic rename over the
//!   running exe; Windows: rename-aside dance), matching install.sh/ps1.

use serde::Deserialize;
use sha2::{Digest, Sha256};
use std::collections::HashMap;
use std::io::Read;
use std::path::{Path, PathBuf};
use std::time::Duration;

pub const DEFAULT_BASE: &str =
    "https://github.com/JohannesBertens/rust-hf-downloader/releases/latest/download";
const MANIFEST_NAME: &str = "latest.json";
/// Hard ceiling for the small JSON manifest fetch.
const MANIFEST_TIMEOUT: Duration = Duration::from_secs(15);
/// Hard ceiling for the asset download (large binaries on slow links).
const ASSET_TIMEOUT: Duration = Duration::from_secs(600);

#[cfg(windows)]
pub const BIN_NAME: &str = "rust-hf-downloader.exe";
#[cfg(not(windows))]
pub const BIN_NAME: &str = "rust-hf-downloader";

/// Release base URL: `RHD_UPDATE_BASE` override or the GitHub default.
pub fn base_url() -> String {
    let base = std::env::var("RHD_UPDATE_BASE").unwrap_or_else(|_| DEFAULT_BASE.to_string());
    base.trim_end_matches('/').to_string()
}

// ---------------------------------------------------------------------------
// Manifest
// ---------------------------------------------------------------------------

/// `latest.json` as generated by the release workflow.
#[derive(Deserialize, Debug)]
pub struct Manifest {
    pub version: String,
    /// Manifest metadata kept for schema completeness / future display.
    #[allow(dead_code)]
    #[serde(default)]
    pub released_at: Option<String>,
    #[serde(default)]
    pub notes_url: Option<String>,
    pub assets: HashMap<String, AssetSpec>,
}

#[derive(Deserialize, Debug, Clone)]
pub struct AssetSpec {
    pub name: String,
    pub format: AssetFormat,
    pub sha256: String,
}

#[derive(Deserialize, Debug, Clone, Copy, PartialEq, Eq)]
#[serde(rename_all = "kebab-case")]
pub enum AssetFormat {
    TarGz,
    Zip,
}

// ---------------------------------------------------------------------------
// Versions
// ---------------------------------------------------------------------------

/// Strict `major.minor.patch` (leading `v` tolerated) — we control the tag
/// format, so no semver machinery is pulled in.
#[derive(Debug, Clone, Copy, PartialEq, Eq, PartialOrd, Ord)]
pub struct VersionTriple {
    pub major: u64,
    pub minor: u64,
    pub patch: u64,
}

impl VersionTriple {
    pub fn parse(s: &str) -> Result<Self, String> {
        let s = s.trim().strip_prefix('v').unwrap_or(s.trim());
        let mut parts = s.split('.');
        let (Some(major), Some(minor), Some(patch), None) =
            (parts.next(), parts.next(), parts.next(), parts.next())
        else {
            return Err(format!("expected `major.minor.patch`, got {s:?}"));
        };
        let parse_num = |v: &str| {
            v.parse::<u64>()
                .map_err(|_| format!("non-numeric version component {v:?}"))
        };
        Ok(VersionTriple {
            major: parse_num(major)?,
            minor: parse_num(minor)?,
            patch: parse_num(patch)?,
        })
    }

    pub fn current() -> Self {
        // Compile-time constant; the parse is exercised by unit tests.
        VersionTriple::parse(env!("CARGO_PKG_VERSION")).expect("CARGO_PKG_VERSION is x.y.z")
    }
}

impl std::fmt::Display for VersionTriple {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        write!(f, "{}.{}.{}", self.major, self.minor, self.patch)
    }
}

// ---------------------------------------------------------------------------
// Platform
// ---------------------------------------------------------------------------

/// The CI asset triple for the *running* binary, or `None` on targets we do
/// not publish release assets for.
pub fn target_triple() -> Option<&'static str> {
    if cfg!(all(target_os = "linux", target_arch = "x86_64")) {
        Some("x86_64-unknown-linux-gnu")
    } else if cfg!(all(target_os = "linux", target_arch = "aarch64")) {
        Some("aarch64-unknown-linux-gnu")
    } else if cfg!(all(target_os = "macos", target_arch = "aarch64")) {
        Some("aarch64-apple-darwin")
    } else if cfg!(all(target_os = "macos", target_arch = "x86_64")) {
        Some("x86_64-apple-darwin")
    } else if cfg!(all(target_os = "windows", target_arch = "x86_64")) {
        Some("x86_64-pc-windows-msvc")
    } else {
        None
    }
}

// ---------------------------------------------------------------------------
// Errors
// ---------------------------------------------------------------------------

#[derive(Debug)]
pub enum UpdateError {
    Network(String),
    UnsupportedPlatform,
    NoAssetForPlatform { triple: String },
    MalformedManifest(String),
    Checksum { expected: String, actual: String },
    Archive(String),
    Swap(String),
    Io(String),
}

impl std::fmt::Display for UpdateError {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        match self {
            UpdateError::Network(m) => write!(f, "network error: {m}"),
            UpdateError::UnsupportedPlatform => write!(
                f,
                "no release assets are published for this platform ({}); \
                 build from source or use the one-liner installer",
                std::env::consts::OS
            ),
            UpdateError::NoAssetForPlatform { triple } => write!(
                f,
                "the latest release has no asset for target `{triple}` \
                 (pre-2.10.0 release?); try again after the next release or \
                 use the one-liner installer"
            ),
            UpdateError::MalformedManifest(m) => write!(f, "malformed latest.json: {m}"),
            UpdateError::Checksum { expected, actual } => write!(
                f,
                "checksum mismatch (expected {expected}, got {actual}); \
                 the download was discarded"
            ),
            UpdateError::Archive(m) => write!(f, "bad release archive: {m}"),
            UpdateError::Swap(m) => write!(f, "could not replace the running binary: {m}"),
            UpdateError::Io(m) => write!(f, "filesystem error: {m}"),
        }
    }
}

impl std::error::Error for UpdateError {}

// ---------------------------------------------------------------------------
// Check
// ---------------------------------------------------------------------------

/// Convenience wrapper for callers that only want the verdict (the TUI's
/// startup check, phase 2 of plans/self-update.md). The CLI's `run_update`
/// composes `fetch_manifest` + `manifest_asset` directly because `--force`
/// needs the asset even when current.
#[allow(dead_code)]
pub enum CheckOutcome {
    Current {
        current: VersionTriple,
    },
    Available {
        current: VersionTriple,
        latest: VersionTriple,
        asset: AssetSpec,
        notes_url: Option<String>,
    },
}

#[allow(dead_code)]
pub async fn check(client: &reqwest::Client, base: &str) -> Result<CheckOutcome, UpdateError> {
    let (manifest, latest) = fetch_manifest(client, base).await?;

    let current = VersionTriple::current();
    let triple = target_triple().ok_or(UpdateError::UnsupportedPlatform)?;
    let asset = manifest_asset(&manifest, triple)?.clone();

    if latest <= current {
        Ok(CheckOutcome::Current { current })
    } else {
        Ok(CheckOutcome::Available {
            current,
            latest,
            asset,
            notes_url: manifest.notes_url,
        })
    }
}

/// Fetches and validates the manifest; returns it with its parsed version.
pub async fn fetch_manifest(
    client: &reqwest::Client,
    base: &str,
) -> Result<(Manifest, VersionTriple), UpdateError> {
    let url = format!("{base}/{MANIFEST_NAME}");
    let resp = client
        .get(&url)
        .timeout(MANIFEST_TIMEOUT)
        .send()
        .await
        .and_then(|r| r.error_for_status())
        .map_err(|e| UpdateError::Network(format!("fetching {url}: {e}")))?;
    let manifest: Manifest = resp
        .json()
        .await
        .map_err(|e| UpdateError::MalformedManifest(format!("fetch {url}: {e}")))?;
    let latest = VersionTriple::parse(&manifest.version).map_err(UpdateError::MalformedManifest)?;
    Ok((manifest, latest))
}

/// Resolves the asset spec for a target triple from a fetched manifest.
pub fn manifest_asset<'a>(
    manifest: &'a Manifest,
    triple: &str,
) -> Result<&'a AssetSpec, UpdateError> {
    manifest
        .assets
        .get(triple)
        .ok_or_else(|| UpdateError::NoAssetForPlatform {
            triple: triple.to_string(),
        })
}

// ---------------------------------------------------------------------------
// Download + verify
// ---------------------------------------------------------------------------

/// Streams the asset into a fresh temp dir, hashing as it goes; verifies the
/// SHA256 against the manifest before returning the path.
pub async fn download_asset(
    client: &reqwest::Client,
    base: &str,
    spec: &AssetSpec,
    progress: &mut (dyn FnMut(u64, u64) + Send + Sync),
) -> Result<PathBuf, UpdateError> {
    let dir = std::env::temp_dir().join(format!("rhd-update-{}", std::process::id()));
    std::fs::create_dir_all(&dir)
        .map_err(|e| UpdateError::Io(format!("creating {}: {e}", dir.display())))?;
    let dest = dir.join(&spec.name);

    let url = format!("{base}/{}", spec.name);
    let mut resp = client
        .get(&url)
        .timeout(ASSET_TIMEOUT)
        .send()
        .await
        .and_then(|r| r.error_for_status())
        .map_err(|e| UpdateError::Network(format!("fetching {url}: {e}")))?;
    let total: u64 = resp.content_length().unwrap_or(0);

    let mut file = std::fs::File::create(&dest)
        .map_err(|e| UpdateError::Io(format!("creating {}: {e}", dest.display())))?;
    let mut hasher = Sha256::new();
    let mut downloaded: u64 = 0;
    while let Some(chunk) = resp
        .chunk()
        .await
        .map_err(|e| UpdateError::Network(format!("streaming {url}: {e}")))?
    {
        use std::io::Write;
        hasher.update(&chunk);
        file.write_all(&chunk)
            .map_err(|e| UpdateError::Io(format!("writing {}: {e}", dest.display())))?;
        downloaded += chunk.len() as u64;
        progress(downloaded, total);
    }
    drop(file);

    let actual = hex::encode(hasher.finalize());
    if !actual.eq_ignore_ascii_case(&spec.sha256) {
        let _ = std::fs::remove_file(&dest);
        return Err(UpdateError::Checksum {
            expected: spec.sha256.clone(),
            actual,
        });
    }
    Ok(dest)
}

// ---------------------------------------------------------------------------
// Extract
// ---------------------------------------------------------------------------

/// Extracts exactly one `rust-hf-downloader[.exe]` member from the release
/// archive into `<archive_dir>/<bin_name>` and returns its path.
pub fn extract_binary(archive: &Path, format: AssetFormat) -> Result<PathBuf, UpdateError> {
    let dest = archive
        .parent()
        .unwrap_or_else(|| Path::new("."))
        .join(BIN_NAME);

    let matches = |name: &str| {
        Path::new(name)
            .file_name()
            .map(|n| n == BIN_NAME)
            .unwrap_or(false)
    };

    let mut found = 0usize;
    match format {
        AssetFormat::TarGz => extract_tar_gz(archive, &matches, &dest, &mut found)?,
        AssetFormat::Zip => extract_zip(archive, &matches, &dest, &mut found)?,
    }

    match found {
        1 => Ok(dest),
        0 => Err(UpdateError::Archive(format!(
            "no `{BIN_NAME}` member found"
        ))),
        n => Err(UpdateError::Archive(format!(
            "archive contains {n} `{BIN_NAME}` members (expected exactly 1)"
        ))),
    }
}

#[cfg(unix)]
fn extract_tar_gz(
    archive: &Path,
    matches: &dyn Fn(&str) -> bool,
    dest: &Path,
    found: &mut usize,
) -> Result<(), UpdateError> {
    use std::io::Write;
    let file = std::fs::File::open(archive)
        .map_err(|e| UpdateError::Archive(format!("open {}: {e}", archive.display())))?;
    let decoder = flate2::read::GzDecoder::new(file);
    let mut tar = tar::Archive::new(decoder);
    for entry in tar
        .entries()
        .map_err(|e| UpdateError::Archive(format!("reading tar: {e}")))?
    {
        let mut entry = entry.map_err(|e| UpdateError::Archive(format!("tar entry: {e}")))?;
        let path = entry
            .path()
            .map_err(|e| UpdateError::Archive(format!("tar entry path: {e}")))?
            .to_path_buf();
        let Some(name) = path.to_str() else {
            continue;
        };
        if !matches(name) {
            continue;
        }
        *found += 1;
        if *found > 1 {
            continue;
        }
        let mut out = std::fs::File::create(dest)
            .map_err(|e| UpdateError::Archive(format!("creating {}: {e}", dest.display())))?;
        let mut bytes = Vec::new();
        entry
            .read_to_end(&mut bytes)
            .map_err(|e| UpdateError::Archive(format!("reading member: {e}")))?;
        out.write_all(&bytes)
            .map_err(|e| UpdateError::Archive(format!("writing {}: {e}", dest.display())))?;
        use std::os::unix::fs::PermissionsExt;
        std::fs::set_permissions(dest, std::fs::Permissions::from_mode(0o755))
            .map_err(|e| UpdateError::Archive(format!("chmod {}: {e}", dest.display())))?;
    }
    Ok(())
}

#[cfg(windows)]
fn extract_tar_gz(
    _archive: &Path,
    _matches: &dyn Fn(&str) -> bool,
    _dest: &Path,
    _found: &mut usize,
) -> Result<(), UpdateError> {
    // Unix assets are never served to Windows binaries (asset triples are
    // platform-mapped); unreachable by construction.
    Err(UpdateError::Archive(
        "tar.gz extraction is Unix-only".into(),
    ))
}

#[cfg(windows)]
fn extract_zip(
    archive: &Path,
    matches: &dyn Fn(&str) -> bool,
    dest: &Path,
    found: &mut usize,
) -> Result<(), UpdateError> {
    let file = std::fs::File::open(archive)
        .map_err(|e| UpdateError::Archive(format!("open {}: {e}", archive.display())))?;
    let mut zip = zip::ZipArchive::new(file)
        .map_err(|e| UpdateError::Archive(format!("reading zip: {e}")))?;
    for i in 0..zip.len() {
        let mut entry = zip
            .by_index(i)
            .map_err(|e| UpdateError::Archive(format!("zip entry {i}: {e}")))?;
        let name = entry.name().to_string();
        if !matches(&name) {
            continue;
        }
        *found += 1;
        if *found > 1 {
            continue;
        }
        let mut out = std::fs::File::create(dest)
            .map_err(|e| UpdateError::Archive(format!("creating {}: {e}", dest.display())))?;
        std::io::copy(&mut entry, &mut out)
            .map_err(|e| UpdateError::Archive(format!("extracting member: {e}")))?;
    }
    Ok(())
}

#[cfg(not(windows))]
fn extract_zip(
    _archive: &Path,
    _matches: &dyn Fn(&str) -> bool,
    _dest: &Path,
    _found: &mut usize,
) -> Result<(), UpdateError> {
    // Windows assets are never served to non-Windows binaries.
    Err(UpdateError::Archive(
        "zip extraction is Windows-only".into(),
    ))
}

// ---------------------------------------------------------------------------
// Swap
// ---------------------------------------------------------------------------

/// Atomically replaces the current executable with `new_binary`
/// (self_replace: Unix rename; Windows rename-aside). The caller's
/// `current_exe` is resolved by the crate itself. Best-effort cleanup of
/// the temp tree stays with the caller.
pub fn swap(_current_exe: &Path, new_binary: &Path) -> Result<(), UpdateError> {
    self_replace::self_replace(new_binary).map_err(|e| UpdateError::Swap(e.to_string()))
}

// ---------------------------------------------------------------------------
// Tests
// ---------------------------------------------------------------------------

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn version_triple_parses_and_orders() {
        assert_eq!(
            VersionTriple::parse("2.10.0"),
            Ok(VersionTriple {
                major: 2,
                minor: 10,
                patch: 0
            })
        );
        assert_eq!(VersionTriple::parse("v3.0.1").unwrap().patch, 1);
        assert!(VersionTriple::parse("2.10").is_err());
        assert!(VersionTriple::parse("2.10.0.1").is_err());
        assert!(VersionTriple::parse("2.x.0").is_err());
        assert!(VersionTriple::parse(" 2.10.0 ").is_ok());

        let a = VersionTriple::parse("2.9.0").unwrap();
        let b = VersionTriple::parse("2.10.0").unwrap();
        assert!(a < b); // numeric compare, not lexicographic ("9" > "10")
        assert_eq!(b.to_string(), "2.10.0");
    }

    #[test]
    fn current_version_parses() {
        // CARGO_PKG_VERSION must always satisfy the strict triple format.
        assert_eq!(
            VersionTriple::parse(env!("CARGO_PKG_VERSION")).unwrap(),
            VersionTriple::current()
        );
    }

    #[test]
    fn target_triple_is_known_on_ci_platforms() {
        // This test binary runs on the same triples CI publishes for.
        assert!(target_triple().is_some());
    }

    #[test]
    fn manifest_parses() {
        let raw = serde_json::json!({
            "version": "2.11.0",
            "released_at": "2026-10-01T00:00:00Z",
            "notes_url": "https://example.com/notes",
            "assets": {
                "x86_64-unknown-linux-gnu": {
                    "name": "rust-hf-downloader-x86_64-unknown-linux-gnu.tar.gz",
                    "format": "tar-gz",
                    "sha256": "aa"
                },
                "x86_64-pc-windows-msvc": {
                    "name": "rust-hf-downloader-x86_64-pc-windows-msvc.zip",
                    "format": "zip",
                    "sha256": "bb"
                }
            }
        });
        let m: Manifest = serde_json::from_value(raw).unwrap();
        assert_eq!(m.version, "2.11.0");
        let lin = m.assets.get("x86_64-unknown-linux-gnu").unwrap();
        assert_eq!(lin.format, AssetFormat::TarGz);
        let win = m.assets.get("x86_64-pc-windows-msvc").unwrap();
        assert_eq!(win.format, AssetFormat::Zip);
    }

    #[test]
    fn manifest_rejects_unknown_format() {
        let raw = serde_json::json!({
            "version": "2.11.0",
            "assets": {
                "t": { "name": "n", "format": "zstd", "sha256": "aa" }
            }
        });
        assert!(serde_json::from_value::<Manifest>(raw).is_err());
    }

    #[test]
    fn base_url_strips_trailing_slash_and_honors_override() {
        // SAFETY: tests run multi-threaded but sequentially within this module.
        let key = "RHD_UPDATE_BASE";
        let prev = std::env::var_os(key);
        unsafe { std::env::set_var(key, "http://mirror.example/releases//") };
        assert_eq!(base_url(), "http://mirror.example/releases");
        match prev {
            Some(v) => unsafe { std::env::set_var(key, v) },
            None => unsafe { std::env::remove_var(key) },
        }
        assert!(!base_url().ends_with('/'));
    }
}
